/**
 * Sample fixture dataset for client-side rendering.
 * In production these come from the backend API; this provides offline/demo data.
 */
import type { Fixture, StandardId } from "./types";

export const sampleFixtures: Fixture[] = [
  {
    id: "FX-001",
    assetTag: "BL-T-001",
    fixtureName: "Main Office Troffer A",
    manufacturer: "Cree Lighting",
    model: "ZR24-40L-835",
    fixtureType: "LED Troffer",
    wattage: 32,
    lumenOutput: 4000,
    cct: 3500,
    cri: 82,
    quantity: 12,
    spaceType: "Office - Open Plan",
    spaceArea: 800,
    applicableStandards: ["ASHRAE_90_1_2022", "DLC_QPL_5_1", "IES_ILLUMINANCE"],
    importSource: "csv",
    importedAt: "2026-03-10T14:30:00Z",
    notes: "Main open office area, 2nd floor",
  },
  {
    id: "FX-002",
    assetTag: "BL-T-002",
    fixtureName: "Conference Room Panel B",
    manufacturer: "Lithonia Lighting",
    model: "CPX-2X4-4000LM",
    fixtureType: "LED Panel",
    wattage: 36,
    lumenOutput: 4200,
    cct: 4000,
    cri: 84,
    quantity: 6,
    spaceType: "Conference/Meeting/Multipurpose",
    spaceArea: 300,
    applicableStandards: ["ASHRAE_90_1_2022", "TITLE_24_2022", "DLC_QPL_5_1"],
    importSource: "manual",
    importedAt: "2026-03-12T09:15:00Z",
    notes: "Large conference room, ground floor",
  },
  {
    id: "FX-003",
    assetTag: "BL-H-003",
    fixtureName: "Warehouse High Bay C",
    manufacturer: "RAB Lighting",
    model: "BAYLED78",
    fixtureType: "LED High Bay",
    wattage: 78,
    lumenOutput: 11200,
    cct: 5000,
    cri: 75,
    quantity: 20,
    spaceType: "Warehouse - Medium/Bulky",
    spaceArea: 5000,
    applicableStandards: ["ASHRAE_90_1_2022", "DLC_QPL_5_1", "IES_ILLUMINANCE"],
    importSource: "xlsx",
    importedAt: "2026-03-14T11:00:00Z",
    notes: "Main warehouse zone A",
  },
  {
    id: "FX-004",
    assetTag: "BL-D-004",
    fixtureName: "Lobby Downlight Set D",
    manufacturer: "Acuity Brands",
    model: "LDN6-10-40K",
    fixtureType: "LED Downlight",
    wattage: 10,
    lumenOutput: 1000,
    cct: 4000,
    cri: 90,
    quantity: 8,
    spaceType: "Lobby - All Other",
    spaceArea: 400,
    applicableStandards: ["ASHRAE_90_1_2022", "IES_ILLUMINANCE", "DLC_QPL_5_1"],
    importSource: "manual",
    importedAt: "2026-03-15T08:45:00Z",
    notes: "Main entrance lobby",
  },
  {
    id: "FX-005",
    assetTag: "BL-P-005",
    fixtureName: "Parking Garage Fixture E",
    manufacturer: "Hubbell Lighting",
    model: "LNC-48L-5K",
    fixtureType: "LED Parking Garage",
    wattage: 48,
    lumenOutput: 5600,
    cct: 5000,
    cri: 72,
    quantity: 30,
    spaceType: "Parking Area Interior",
    spaceArea: 12000,
    applicableStandards: ["ASHRAE_90_1_2022", "IECC_2021", "DLC_QPL_5_1"],
    importSource: "csv",
    importedAt: "2026-03-16T13:20:00Z",
    notes: "Underground parking level B1",
  },
  {
    id: "FX-006",
    assetTag: "BL-S-006",
    fixtureName: "Stairwell Vapor Tight F",
    manufacturer: "Eaton",
    model: "VT4-LED-2X4",
    fixtureType: "LED Vapor Tight",
    wattage: 25,
    lumenOutput: 3200,
    cct: 4000,
    cri: 80,
    quantity: 4,
    spaceType: "Stairwell",
    spaceArea: 120,
    applicableStandards: ["ASHRAE_90_1_2022", "DLC_QPL_5_1"],
    importSource: "manual",
    importedAt: "2026-03-17T10:00:00Z",
    notes: "North stairwell, floors 1-4",
  },
  {
    id: "FX-007",
    assetTag: "BL-W-007",
    fixtureName: "Loading Dock Wall Pack G",
    manufacturer: "RAB Lighting",
    model: "WP3LED150",
    fixtureType: "LED Wall Pack",
    wattage: 150,
    lumenOutput: 15000,
    cct: 5000,
    cri: 70,
    quantity: 2,
    spaceType: "Loading Dock Interior",
    spaceArea: 600,
    applicableStandards: ["ASHRAE_90_1_2022", "DLC_QPL_5_1"],
    importSource: "csv",
    importedAt: "2026-03-18T16:30:00Z",
    notes: "Rear loading dock — HIGH WATTAGE for review",
  },
  {
    id: "FX-008",
    assetTag: "BL-R-008",
    fixtureName: "Retail Display Track H",
    manufacturer: "Cooper Lighting",
    model: "TRK-LED-30W",
    fixtureType: "LED Track Light",
    wattage: 30,
    lumenOutput: 2400,
    cct: 3000,
    cri: 92,
    quantity: 15,
    spaceType: "Retail Sales Area",
    spaceArea: 600,
    applicableStandards: ["ASHRAE_90_1_2022", "TITLE_24_2022", "IES_ILLUMINANCE"],
    importSource: "xlsx",
    importedAt: "2026-03-19T09:00:00Z",
    notes: "Ground floor retail, south wing",
  },
  {
    id: "FX-009",
    assetTag: "BL-C-009",
    fixtureName: "Corridor Strip I",
    manufacturer: "Philips",
    model: "RC125B-LED36S",
    fixtureType: "LED Strip",
    wattage: 18,
    lumenOutput: 2200,
    cct: 4000,
    cri: 83,
    quantity: 10,
    spaceType: "Corridor",
    spaceArea: 500,
    applicableStandards: ["ASHRAE_90_1_2022", "IES_ILLUMINANCE", "DLC_QPL_5_1"],
    importSource: "manual",
    importedAt: "2026-03-20T11:30:00Z",
    notes: "2nd floor east corridor",
  },
  {
    id: "FX-010",
    assetTag: "BL-E-010",
    fixtureName: "Emergency Exit Sign J",
    manufacturer: "Lithonia Lighting",
    model: "LQM-S-W-3-R-120/277",
    fixtureType: "LED Exit Sign",
    wattage: 2,
    lumenOutput: 90,
    cct: 0,
    cri: 0,
    quantity: 8,
    spaceType: "Corridor",
    spaceArea: 500,
    applicableStandards: ["DLC_QPL_5_1"],
    importSource: "manual",
    importedAt: "2026-03-21T14:00:00Z",
    notes: "Emergency exit signage, all floors",
  },
  {
    id: "FX-011",
    assetTag: "BL-K-011",
    fixtureName: "Kitchen Prep Canopy K",
    manufacturer: "MaxLite",
    model: "LSC-40UL-50",
    fixtureType: "LED Canopy",
    wattage: 40,
    lumenOutput: 4800,
    cct: 5000,
    cri: 80,
    quantity: 4,
    spaceType: "Food Preparation Area",
    spaceArea: 350,
    applicableStandards: ["ASHRAE_90_1_2022", "DLC_QPL_5_1", "IES_ILLUMINANCE"],
    importSource: "csv",
    importedAt: "2026-03-22T08:00:00Z",
    notes: "Commercial kitchen, basement level",
  },
  {
    id: "FX-012",
    assetTag: "BL-L-012",
    fixtureName: "Lab Pendant L",
    manufacturer: "Finelite",
    model: "HP-6-LED-DIM",
    fixtureType: "LED Pendant",
    wattage: 54,
    lumenOutput: 5400,
    cct: 4000,
    cri: 90,
    quantity: 8,
    spaceType: "Laboratory - Medical/Industrial/Research",
    spaceArea: 500,
    applicableStandards: ["ASHRAE_90_1_2022", "IES_ILLUMINANCE", "DLC_QPL_5_1"],
    importSource: "xlsx",
    importedAt: "2026-03-22T10:30:00Z",
    notes: "Research lab, 3rd floor",
  },
];
